name: wallpapers
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'
  



dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
