// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMspEO1PM2grt152Fl2f3rKqDdm8-e4Hs',
    appId: '1:630232633313:web:84e33587de2fb4c3ff0ca0',
    messagingSenderId: '630232633313',
    projectId: 'wallpapers-7cc40',
    authDomain: 'wallpapers-7cc40.firebaseapp.com',
    storageBucket: 'wallpapers-7cc40.appspot.com',
    measurementId: 'G-4CHMLCSCS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL88ieWRVhltqcNTZwETw49jY63T4DcCc',
    appId: '1:630232633313:android:8c786206ff4b6df0ff0ca0',
    messagingSenderId: '630232633313',
    projectId: 'wallpapers-7cc40',
    storageBucket: 'wallpapers-7cc40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbvooe2W1_JXgUW0P6SWc_xHdDkdOivZE',
    appId: '1:630232633313:ios:5150f91881fe3640ff0ca0',
    messagingSenderId: '630232633313',
    projectId: 'wallpapers-7cc40',
    storageBucket: 'wallpapers-7cc40.appspot.com',
    iosClientId: '630232633313-ccpd2dccg14av96lkt6gf2aj4artdcda.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpapers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbvooe2W1_JXgUW0P6SWc_xHdDkdOivZE',
    appId: '1:630232633313:ios:3852bf6afe31b0bcff0ca0',
    messagingSenderId: '630232633313',
    projectId: 'wallpapers-7cc40',
    storageBucket: 'wallpapers-7cc40.appspot.com',
    iosClientId: '630232633313-d2at5i35ag490kudecd028dimf5jep1a.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallpapers.RunnerTests',
  );
}
